# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  code-quality-workflow-setup:
    name: Run Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate


  unit-tests:
    runs-on: ubuntu-latest
    needs: [code-quality-workflow-setup]
    steps:
      - name: Run tests
        run: php artisan test

  phpstan:
    runs-on: ubuntu-latest
    needs: [code-quality-workflow-setup]
    steps:
      - name: PHPStan Analysis
        uses: php-actions/phpstan@v3
        with:
          configuration: phpstan.neon
          path: app/ tests/

  code-formatting:
    runs-on: ubuntu-latest
    needs: [code-quality-workflow-setup]
    steps:
      - name: Code Formating
        run: php ./vendor/bin/pint --config pint.json --test
